# Criteria for what fragments to include
min_percent: 0.02
min_count: 100
isotopes: True
NLs: False
immonium_ions: False
a_ions: False
b_ions: True
y_ions: True
precursor_ions: True
internal_ions: False