dic_config: /scratch1/fs1/d.goldfarb/Backpack/training/byp_weighted_normTot_noRootNCEMean/saved_model/data.yaml
model_config: /scratch1/fs1/d.goldfarb/Backpack/training/byp_weighted_normTot_noRootNCEMean/saved_model/model_config.yaml
model_ckpt: /scratch1/fs1/d.goldfarb/Backpack/training/byp_weighted_normTot_noRootNCEMean/saved_model/ckpt_step1191168_0.9033
enable_gpu: True

to_predict: /storage1/fs1/d.goldfarb/Active/RIS_Goldfarb_Lab/NTW/ASMS_2024/UNISPEC_LIBS/UNISPEC_LIBS/for_unispec/unispec_HUMAN_YEAST_ECOLI_1var_1mc_chronologer_050624.tsv
out_file: /storage1/fs1/d.goldfarb/Active/RIS_Goldfarb_Lab/NTW/ASMS_2024/UNISPEC_LIBS/UNISPEC_LIBS/for_unispec/unispec_HUMAN_YEAST_ECOLI_1var_1mc_chronologer_050624.msp.by_exploris27_v2

batch_size: 100

search_empty_pos: True
dsets:
   valuniq: 
      msp: path/to/valuniq/ValidUniq2022418_2023J1_edit.msp
   valsim:
      msp: path/to/valsim/ValidSim2022418_mPhos_edit.msp
   valcom:
      msp: path/to/valcom/ValidCom2022418_mPhos_edit.msp
   test:
      msp: path/to/test/TestUniq202277_2023J1.msp
dsetspred:
   valuniqps:
      msp: predictions/valuniq_ps.msp
   valsimps:
      msp: predictions/valsim_ps.msp
   valcomps:
      msp: predictions/valcom_ps.msp
   valuniq:
      msp: predictions/valuniq_pred.msp
   test:
      msp: predictions/test_pred.msp
mode: interactive
write_msp:
   label_type: 
   label_path: 'path/to/labels/HMPhos_labels16.txt'
   dset: valcom
   comments_path: 'path/to/comments/HMPhos_comments.txt'
   cecorr: 0
   print_every: 2000
   outfn: "temp/aout"
calc_cs:
   predset: test
   rawset: test
   map_path:
   closest_match: False
   CSkwargs:
   outfn: "test.cs"