#dic_config: /scratch1/fs1/d.goldfarb/Backpack/training/byp_nl_decon2/saved_model/4M-data.yaml
#model_config: /scratch1/fs1/d.goldfarb/Backpack/training/byp_nl_decon2/saved_model/4M-model_config.yaml
#model_ckpt: /scratch1/fs1/d.goldfarb/Backpack/training/byp_nl_decon2/saved_model/4M.ckpt
dic_config: /scratch1/fs1/d.goldfarb/Backpack/training/byp_imm5_SA_roll_12hr/saved_model/data.yaml
model_config: /scratch1/fs1/d.goldfarb/Backpack/training/byp_imm5_SA_roll_12hr/saved_model/model_config.yaml
model_ckpt: /scratch1/fs1/d.goldfarb/Backpack/training/byp_imm5_SA_roll_12hr/saved_model/e14.ckpt
enable_gpu: True

#to_predict: /storage1/fs1/d.goldfarb/Active/RIS_Goldfarb_Lab/NTW/PIONEER/PIONEER_PAPER/SPEC_LIBS/AltimiterOct13Version/Altimeter101324_MixedSpecies_OlsenAstral_NoEntrapment_101324.poin/precursors_for_altimiter.csv
to_predict: /scratch1/fs1/d.goldfarb/Backpack/eval/pickle/human.csv
out_file: /storage1/fs1/d.goldfarb/Active/Backpack/libraries/human/byp_imm5_prosit_ewm2hr/Altimeter
#out_file: /scratch1/fs1/d.goldfarb/Backpack/libraries/astral/Altimeter101324_MixedSpecies_OlsenAstral_NoEntrapment_101324_smooth-b31/Altimeter
#out_file: /storage1/fs1/d.goldfarb/Active/Backpack/libraries/astral/Altimeter101324_MixedSpecies_OlsenAstral_NoEntrapment_101324_bright-u10/Altimeter
#out_file: /storage1/fs1/d.goldfarb/Active/Backpack/libraries/exploris/Altimeter101324_MixedSpecies_OlsenAstral_NoEntrapment_101324_clear-b5/Altimeter

batch_size: 1000

search_empty_pos: True
dsets:
   valuniq: 
      msp: path/to/valuniq/ValidUniq2022418_2023J1_edit.msp
   valsim:
      msp: path/to/valsim/ValidSim2022418_mPhos_edit.msp
   valcom:
      msp: path/to/valcom/ValidCom2022418_mPhos_edit.msp
   test:
      msp: path/to/test/TestUniq202277_2023J1.msp
dsetspred:
   valuniqps:
      msp: predictions/valuniq_ps.msp
   valsimps:
      msp: predictions/valsim_ps.msp
   valcomps:
      msp: predictions/valcom_ps.msp
   valuniq:
      msp: predictions/valuniq_pred.msp
   test:
      msp: predictions/test_pred.msp
mode: interactive
write_msp:
   label_type: 
   label_path: 'path/to/labels/HMPhos_labels16.txt'
   dset: valcom
   comments_path: 'path/to/comments/HMPhos_comments.txt'
   cecorr: 0
   print_every: 2000
   outfn: "temp/aout"
calc_cs:
   predset: test
   rawset: test
   map_path:
   closest_match: False
   CSkwargs:
   outfn: "test.cs"